# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- story/130897-apply-use-eslint-dashboard-project

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
    checkLatest: true
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: 'npm run lint'
  displayName: 'Run lint'

- task: ArchiveFiles@2
  displayName: 'Archive myaccess-2.0-dashboard'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist/myaccess-2.0-dashboard'
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/dist.zip'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'